# Generated by Django 4.2.3 on 2023-07-23 09:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created_at', models.DateField(default=datetime.datetime(2023, 7, 23, 9, 6, 13, 564550))),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='www.google.com', storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casinoblogapp.blog')),
            ],
        ),
    ]
